version: '3'
services:

  inewgent_api:
    container_name: inewgent_api
    build: .
    command: pm2-dev ./app/server.js
    environment:
      NODE_ENV: development
    ports:
      - '5000:5000'
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
    networks:
      network-inewgent:

networks:
  network-inewgent:
    external: true
      